version: 1
subgraphs:
  - name: workflows
    routing_url: https://staging.workflows.diamond.ac.uk/graphql
    subscription:
      url: wss://workflows.diamond.ac.uk/graphql/ws
      protocol: ws
    schema:
      file: schema/workflows.graphql
  - name: instrument_sessions
    routing_url: https://instrument-sessions.diamond.ac.uk/api/graphql
    schema:
      file: schema/instrument_sessions.graphql
  - name: samples
    routing_url: https://sample-information.diamond.ac.uk/api/graphql
    schema:
      file: schema/samples.graphql
