router:
  existingConfigmap: ""
  configuration:
    graphApiToken: ""
    routerConfigPath: "/etc/cosmo/execution-config.json"
    cdnUrl: ""
    controlplaneUrl: ""
    otelCollectorUrl: ""
    graphqlMetricsCollectorUrl: ""
    devMode: false

  image:
    registry: ghcr.io
    repository: wundergraph/cosmo/router
    tag: "latest"
    version: "latest"

  env:
    - name: ROUTER_CONFIG_PATH
      value: "/etc/cosmo/execution-config.json"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8088"
    prometheus.io/path: "/metrics"

  commonConfiguration: |-
    version: "1"
    log_level: "debug"
    json_log: true

    listen_addr: "0.0.0.0:3002"

    health_check_path: "/health"
    readiness_check_path: "/health/ready"
    liveness_check_path: "/health/live"

    query_plans_enabled: true
    playground:
      enabled: true
      path: "/"

    cors:
      allow_origins:
        - "*"

    headers:
      all:
        request:
          - op: "propagate"
            named: Authorization
          - op: "propagate"
            named: Cookie

    subgraph_error_propagation:
      mode: wrapped
      allowed_extension_fields:
        - "code"
      propagate_status_codes: true
      attach_service_name: true
      omit_locations: true
      omit_extensions: false
      default_extension_code: DOWNSTREAM_SERVICE_ERROR

    telemetry:
      service_name: "cosmo-router"
      tracing:
        enabled: true
        exporters:
          - endpoint: "http://graph-monitoring-opentelemetry-collector:4317"
            exporter: "grpc"
      metrics:
        prometheus:
          enabled: true
          listen_addr: "0.0.0.0:8088"
        otlp:
          enabled: true
          exporters:
            - endpoint: "http://graph-monitoring-opentelemetry-collector:4317"
              exporter: "grpc"

  extraVolumes: null

  extraVolumeMounts:
    - name: router-execution-config
      mountPath: /etc/cosmo
      readOnly: true

  resources:
    requests:
      cpu: 8
      memory: 4Gi
    limits:
      cpu: 16
      memory: 8Gi

oauth2-proxy:
  enabled: true
  ingress:
    enabled: true
    hostname: graph.diamond.ac.uk
    pathType: Prefix
    hosts:
      - graph.diamond.ac.uk
    path: /
  config:
    configFile: |-
      skip_provider_button = true
      email_domains = [
        "diamond.ac.uk"
      ]
      skip_auth_routes = [
        "POST=^/$",
        "OPTIONS=^/$"
      ]
  alphaConfig:
    enabled: true
    configData:
      injectRequestHeaders:
        - name: Authorization
          values:
            - claim: access_token
              prefix: "Bearer "
          preserveRequestValue: true
      injectResponseHeaders:
        - name: Identity
          values:
            - claim: id_token
      providers:
        - provider: oidc
          scope: "openid profile email fedid"
          clientId: graph
          clientSecretFile: /etc/alpha/client-secret
          id: authn
          oidcConfig:
            issuerURL: https://authn.diamond.ac.uk/realms/master
            insecureAllowUnverifiedEmail: true
            audienceClaims:
              - aud
            emailClaim: email
            userIDClaim: email
    configFile: |
      upstreamConfig:
        upstreams:
          - id: router
            path: /
            uri: http://graph-nightly-router:3002
  extraVolumes:
    - name: client-secret
      secret:
        secretName: "graph-nightly-oauth2-client"
        items:
          - key: secret
            path: client-secret
  extraVolumeMounts:
    - name: client-secret
      mountPath: /etc/alpha
      readOnly: true
