router:
  existingConfigmap: ""
  configuration:
    graphApiToken: ""
    routerConfigPath: "/etc/cosmo/execution-config.json"
    cdnUrl: ""
    controlplaneUrl: ""
    otelCollectorUrl: ""
    graphqlMetricsCollectorUrl: ""
    devMode: false

  image:
    registry: ghcr.io
    repository: wundergraph/cosmo/router
    tag: "latest"
    version: "latest"

  env:
    - name: ROUTER_CONFIG_PATH
      value: "/etc/cosmo/execution-config.json"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8088"
    prometheus.io/path: "/metrics"

  resources:
    requests:
      cpu: 8
      memory: 4Gi
    limits:
      cpu: 16
      memory: 8Gi

oauth2-proxy:
  enabled: true
  ingress:
    enabled: true
    hostname: graph.diamond.ac.uk
    pathType: Prefix
    hosts:
      - graph.diamond.ac.uk
    path: /
  config:
    configFile: |-
      skip_provider_button = true
      email_domains = [
        "diamond.ac.uk"
      ]
      skip_auth_routes = [
        "POST=^/$",
        "OPTIONS=^/$"
      ]
