apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-nightly
  namespace: {{.Release.Namespace}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{default .Release.Namespace .Values.project}}
  sources:
    - repoURL: {{.Values.graph.repoURL}}
      targetRevision: {{.Values.graph.nightlyRevision}}
      path: {{.Values.graph.path}}
      helm:
        valuesObject:
          router:
            commonConfiguration: |-
              {{ .Values.router.commonConfiguration | nindent 14 }}
              telemetry:
                service_name: "router-nightly"

            extraVolumes:
              - name: router-execution-config
                configMap:
                  name: "graph-nightly-router-execution-config"
                  items:
                    - key: execution-config.json
                      path: execution-config.json

            extraVolumeMounts:
              - name: router-execution-config
                mountPath: /etc/cosmo
                readOnly: true

          oauth2-proxy:
            ingress:
              enabled: true
              hostname: graph-nightly.diamond.ac.uk
              hosts:
                - graph-nightly.diamond.ac.uk
              annotations:
                nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
                nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
                nginx.ingress.kubernetes.io/websocket-services: "graph-nightly-oauth2-proxy"

            alphaConfig:
              enabled: true
              configData:
                providers:
                  - clientId: graph-nightly
              configFile: |
                upstreamConfig:
                  upstreams:
                    - id: router
                      path: /
                      uri: http://graph-nightly-router:3002

            extraVolumes:
              - name: client-secret
                secret:
                  secretName: "graph-nightly-oauth2-client"
                  items:
                    - key: secret
                      path: client-secret

            extraVolumeMounts:
              - name: client-secret
                mountPath: /etc/alpha
                readOnly: true

    - repoURL: {{.Values.schema.repoURL}}
      chart: {{.Values.schema.chart}}
      targetRevision: {{.Values.schema.nightlyRevision | quote}}

  destination:
    name: {{.Values.destination.name}}
    server: {{.Values.destination.server}}
    namespace: {{default .Release.Namespace .Values.destination.namespace}}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
