apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-nightly
  namespace: {{.Release.Namespace}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{default .Release.Namespace .Values.project}}
  sources:
    - repoURL: {{.Values.graph.repoURL}}
      targetRevision: {{.Values.graph.nightlyRevision}}
      path: {{.Values.graph.path}}
      helm:
        valuesObject:
          cosmo-gateway:
            enabled: true
            image:
              repository: ghcr.io/wundergraph/cosmo/router
              tag: "0.266.0"
            podAnnotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "4000"
            args:
              - --supergraph=/etc/cosmo/supergraph.graphql
              - --listen=0.0.0.0:4000
              - --forward-headers=Authorization
              - --cors-allowed-origins=^https:\/\/([a-zA-Z0-9\-]+\.)*diamond\.ac\.uk\/?,^https?:\/\/localhost(:\d+)?\/?
              - --otel-endpoint=http://graph-monitoring-opentelemetry-collector:4317
              - --otel-service-name=router-nightly
          oauth2-proxy:
            ingress:
              hostname: graph-nightly.diamond.ac.uk
              hosts:
                - graph-nightly.diamond.ac.uk
            alphaConfig:
              configData:
                providers:
                  - provider: oidc
                    scope: "openid profile email fedid"
                    clientId: graph-nightly
                    clientSecretFile: /etc/alpha/client-secret
                    id: authn
                    oidcConfig:
                      issuerURL: https://authn.diamond.ac.uk/realms/master
                      insecureAllowUnverifiedEmail: true
                      audienceClaims:
                        - aud
                      emailClaim: email
                      userIDClaim: email
    - repoURL: {{.Values.schema.repoURL}}
      chart: {{.Values.schema.chart}}
      targetRevision: {{.Values.schema.nightlyRevision | quote}}
  destination:
    name: {{.Values.destination.name}}
    server: {{.Values.destination.server}}
    namespace: {{default .Release.Namespace .Values.destination.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
