apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-stable
  namespace: {{.Release.Namespace}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{default .Release.Namespace .Values.project}}

  sources:
    - repoURL: {{.Values.graph.repoURL}}
      targetRevision: {{.Values.graph.stableRevision}}
      path: {{.Values.graph.path}}
      helm:
        valuesObject:
          router:
            commonConfiguration: |-
              version: "1"
              log_level: "debug"
              json_log: true

              listen_addr: "0.0.0.0:3002"

              health_check_path: "/health"
              readiness_check_path: "/health/ready"
              liveness_check_path: "/health/live"

              playground_enabled: true
              playground_path: "/"
              introspection:
                enabled: true

              cors:
                allow_origins:
                  - "*"

              headers:
                all:
                  request:
                    - op: "propagate"
                      named: Authorization
                    - op: "propagate"
                      named: Cookie

              subgraph_error_propagation:
                mode: wrapped
                allowed_extension_fields:
                  - "code"
                propagate_status_codes: true
                attach_service_name: true
                omit_locations: true
                omit_extensions: false
                default_extension_code: DOWNSTREAM_SERVICE_ERROR

              telemetry:
                service_name: "router-stable"
                tracing:
                  enabled: true
                  exporters:
                    - endpoint: "http://graph-monitoring-opentelemetry-collector:4317"
                      exporter: "grpc"
                metrics:
                  prometheus:
                    enabled: true
                    listen_addr: "0.0.0.0:8088"
                  otlp:
                    enabled: true
                    exporters:
                      - endpoint: "http://graph-monitoring-opentelemetry-collector:4317"
                        exporter: "grpc"

            extraVolumes:
              - name: router-execution-config
                configMap:
                  name: "graph-stable-router-execution-config"
                  items:
                    - key: execution-config.json
                      path: execution-config.json

            extraVolumeMounts:
              - name: router-execution-config
                mountPath: /etc/cosmo
                readOnly: true

          oauth2-proxy:
            ingress:
              enabled: true
              hostname: graph-stable.diamond.ac.uk
              hosts:
                - graph-stable.diamond.ac.uk
              annotations:
                nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
                nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
                nginx.ingress.kubernetes.io/websocket-services: "graph-stable-oauth2-proxy"
                nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
                nginx.ingress.kubernetes.io/proxy-methods: "POST,GET,OPTIONS"

            alphaConfig:
              enabled: true
              configData:
                providers:
                  - provider: oidc
                    scope: "openid profile email fedid"
                    clientId: graph-stable
                    clientSecretFile: /etc/alpha/client-secret
                    id: authn
                    oidcConfig:
                      issuerURL: https://authn.diamond.ac.uk/realms/master
                      insecureAllowUnverifiedEmail: true
                      audienceClaims:
                        - aud
                      emailClaim: email
                      userIDClaim: email
              configFile: |
                upstreamConfig:
                  upstreams:
                    - id: router
                      path: /
                      uri: http://graph-stable-router:3002
                      allowed_methods:
                        - GET
                        - POST
                        - OPTIONS

            extraVolumes:
              - name: client-secret
                secret:
                  secretName: "graph-stable-oauth2-client"
                  items:
                    - key: secret
                      path: client-secret

            extraVolumeMounts:
              - name: client-secret
                mountPath: /etc/alpha
                readOnly: true

    - repoURL: {{.Values.schema.repoURL}}
      chart: {{.Values.schema.chart}}
      targetRevision: {{.Values.schema.stableRevision | quote}}

  destination:
    name: {{.Values.destination.name}}
    server: {{.Values.destination.server}}
    namespace: {{default .Release.Namespace .Values.destination.namespace}}

  syncPolicy:
    automated:
      prune: true
