apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: "{{ .Release.Name }}-oauth2-client"
  namespace: graph
spec:
  template:
    type: Opaque
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: "{{ .Release.Name }}-oauth2-client"
      namespace: graph
  encryptedData:
    secret: AgAVXOR+MM/s67OWwjL3wXMX3Sg2JUnF4Zl7a57VMJzKRyvkC44CvyfQ+DzVGLkc7GuVgVM8Ha06wDD3cx3MH0WgauGIsCprpw2nA3fQJAdFhIWs0OfIF/UH9gxM7zIQVcheTo3sA61vrEeesmx9L5zaA5MP6+bFKjecvcFDydMDkksu/PD7cyZFereIr8X2YWSDv2GTMMskASo+LWcHFYWVO/NAoHPnnhgXDKEmvsfY3fNK+q+1F2WFecOGMXmd7v+9H3YARMbH1uUOv6FasPXkwXWKvQfJh7HUIJcv4nhW9qdikqud8FgIV77AVX8rfM2L2icbR4XyaiZ6BAmC2Szz7PVgoO0ILt7lTklsr98oY6/M6h+O0MhR/tm7oN4TAlfnPQmnxzQzNHUd1yrnETPKch/rhksFSdF9dFKLfWIZR2ezHeL8cGuv6xwZeUdKEBTbSSfgFjc4atpRMx1OKLHqYApIEWZ/PhYw3vK9m3UFWxlqCPTV+mB1c43iMsftn8f4w0vSuNd5QN+gZbG37gJ92u3i20P+hhELE1KnK/HqHHhP9J+lE1i6qJNQaCee2cRRGyhjTgO7SFEj3PRUCp98huff+PA0WmBdfRpXhY2I7gbA6iiwT2oGdJVQM4yGdkVN8FAEAx52/w0HpJ5wX40VXfPkbmEvupPTiGvgrtvzP7tI0sTe4u7X0TdxulEIGf9qTDN3O7tcqGCztFkfSuavkqtrnGT/myxcSgD9IMkbpg==
