{{ $clientId := (index (index .Values "oauth2-proxy").alphaConfig.configData.providers 0).clientId }}
{{- if eq $clientId "graph" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    authn.diamond.ac.uk/client-id: {{ $clientId }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: "{{ .Release.Name }}-oauth2-client"
  namespace: graph
spec:
  template:
    type: Opaque
    metadata:
      annotations:
        authn.diamond.ac.uk/client-id: {{ $clientId }}
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: "{{ .Release.Name }}-oauth2-client"
      namespace: graph
  encryptedData:
    secret: AgAtgKb1YN4jo+nZjj/s+BcwUjVEzGq/hMjvuhVC+1kF5WM4QZqo3bdaV0Oo3DZKc5flqYy4wa6Jgdx09OxvSbSSPuFIB9v05fpPTuulFgfCAIA7iF1H9zx9WwdjpnXO5x9TStithCPBrBl1Bx4WwTYdMn+k7niiblGX5xiiH6WKhkAOK3cBevyFEH/rNbw3m+GaZ81ViG7FqdD4OX31+CSFYFzHezPCDFYxt8im+SO0ZyO+6zNNLQBiNcPPGsh+o37x+X0kFhlLdcu7eIKzURaMYI52sk+i+GXcN7ro9RWI7rax+0HC1xRbPzBLkves7Oec/p3TPD1eu94QdKCXPdCUsqNAFUPaRI70W5cGSw32UZ1ch4wFyOEbvD/s4FDgfGcK4IYCqoYJ46Bm6ZhAhA6LtqC37uriORpVEAs2cHuMqjJ90ndbP93ELImB9zCZteuY/EeTgh0SxrTYlhg53TnML1oz42+Ei+ZiatFK+JuolCzBTcLN1JUp08suZ1T1B19rHDvI+bCwoNcSWk97HDk44Rz1bX3xEOb+sSnFOvdxQNRBBiJhyPBOOQJSigN0FvcatJqHAuuMb5WYdHd6k7mbrfPiwtirWBLe0t7RTD1TQf1JXfGUWEv8R4cxAE3kWC+gbt6x3mdkPDr0hVFq+c8JHRatc2K99F73F1rG+qYjCF3U+w0r0nlEpzeiHpERP9gnZtylUJ11FHfA4vt+HVDrDhyq9+MYOCFUT3634iQgmA==
{{- else if eq $clientId "graph-nightly" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    authn.diamond.ac.uk/client-id: {{ $clientId }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: "{{ .Release.Name }}-oauth2-client"
  namespace: graph
spec:
  template:
    metadata:
      annotations:
        authn.diamond.ac.uk/client-id: {{ $clientId }}
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: "{{ .Release.Name }}-oauth2-client"
      namespace: graph
  encryptedData:
    secret: AgALA2oO4T4/o7jxEpbOoSVt1P/7hXY5TlqHdg60XQsSaHThxZoQK+RvwrdpQSu31AblNhpmTT7foMujfmpB379fsr5ipJ6/D1AVIuY+5PAOtQE8VhYIrP/n0fRuVHkGipoQIDomq6FG0F55hZsggmzv0l/XffLVepX078Ss3pUiZUIhHHPPhDucG4FfxDG50ZbaiJJ/+RSlhNntDlocsVYBTH0s840nddC/GJGCw5/zlNGFLhLfE0yXDJn4VYDveq/JZmCb6FoLjJF11dvOshGPMKHTNPG6xphBi/Lk4uho/tFgT3/EE6hONaNlH9G8qXKLphboCf8f78+OkwHrOokg5ly7LYYQqMDpgDc0MXWvHU19V7ynbSwX9zfZk9ojF1EGoa4YD1bmb2dGL9NfUsyUAIKNHlyOAFamYS87PVux/hKq1mwQw4FR1fiDYAaMUo0afxlZQR7JvqKzLcY4uvVbEMj/KnDuaboToP3v3X4AUZm/kze0rwsEyopy73EVkQmwJt+JpCYJD6X0U1cnXa3vrWhaSABj1wmjHWumV6evW8aNMPqv6QT8ShyYeP0I9ReA/QSvZR+kFJPF+n5YjduAeXZVtzbAcRnYcTskPRHEv+TTqFFv0aQoyKwNe9495DybOHv3DGpi4HB6bYqUMnetmQDjU39BJ+dTm6WvWqkMrYxxQknlq4Ajg0odogkkt/eOgooIVGI6P5iK4NE45XzwenuIxeDT26X7nGutqjQL/Q==
{{- end }}
