{{ $clientId := (index (index .Values "oauth2-proxy").alphaConfig.configData.providers 0).clientId }}
{{- if eq $clientId "graph" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    authn.diamond.ac.uk/client-id: {{ $clientId }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: "{{ .Release.Name }}-oauth2-client"
  namespace: graph
spec:
  template:
    type: Opaque
    metadata:
      annotations:
        authn.diamond.ac.uk/client-id: {{ $clientId }}
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: "{{ .Release.Name }}-oauth2-client"
      namespace: graph
  encryptedData:
    secret: AgBUgtF/hs/jn0bua0kXFFDLeaH7Os0H5Bbiu9q5TdW3MtxWlkMH73GXCT6WBKaH4hNwzyrhJTnFf4hR3qev/kTzmvoXPZWE759l1qMjG5a5lmrVktlrF+GBHDSsY4l78VYgZ7crYirKy9fC77P8E6whyMoUFSpaKPcDvbyjOTeKkLx621OZTjwAEIyxuUC4zYUPyQiqzLMVRPTLZYENu3P2VWkAeEKmgABNeqi/VVfoDb7HmBuEmgUF8NWDkafksJ1puWBlT9KxgBbHGVWYC65Ji5hvHjALLRkDioxvp2N3HTJBqKH/2ndvTAbS1mTyVFC2Y7CyWBZFA2FBc2xNqUyKxNAYbUsZiUPuTJoOEZW935lrgwn4JxOUnPcx3q1GVDYebNfYXeaTtV7tBWrXbtqgz+zehE7rG52Fb2aaXNVuz6h3CAOLzhhcNwgb+zz/+VeeuHd5HI5cWP8ej8X5QcR4jjEk8E+DnS1vIwg2FJnc3CSBXotgzorMh+m5hWqYwmSJ80VTsQu+lM50KoWYKtERMZYfpG/HZ4wHLLby9OAcb+0kNoKYpASFcjpA42RfmlSLAg/NOMXhWQn1ot/QGEEUvd7RgfaJMutUmh3O1N/7hJC5upYpF4aUdVczm4sj3b16EbMWAF1orphbWNDhqChPZda+iuDnf0QpjyDFtvpHSnMm0cd34WO6GkiOJrSTnKZ7/Vrv1MAw16K66LmP2BW4iafywNzUkyj8Eqmq/Gtb7A==
{{- else if eq $clientId "graph-nightly" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    authn.diamond.ac.uk/client-id: {{ $clientId }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: "{{ .Release.Name }}-oauth2-client"
  namespace: graph
spec:
  template:
    metadata:
      annotations:
        authn.diamond.ac.uk/client-id: {{ $clientId }}
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: "{{ .Release.Name }}-oauth2-client"
      namespace: graph
  encryptedData:
    secret: AgCjE7inLKbwt9xKe3a8QNdYMZkH2efmQqi/ZNwsjx0D6d1yrl4uQ0nZN4WNlcB5NrmtjcT6A6oFfBDgABdr1sd17ywijQjac72k9by3dOyG0Nhq39kvTp8hIknyc/ZXDZNK99PsjHmmN6kVSVl1VwpzJBhzQVzx7VmZBI8a/POngZRlsr9TRhMguyTbkV4J76yUkv4l753WiTMAPoIn174UKIpgJ3+r4OMTPOTGmsf+iX9lT0b+PcXZCPpTkelsOQIAk/kWomJDg6vCUWIu7JdjQCQUq3QobruY3/7c3bs40aap+BMQ+m2a7gHBhcgK/kGQUGLUO2dMOVE/WPwI7ktMQdzW7xF3ydKQQa6HkPKH9B1ytHDkse6ej7+aybMRnDNseyPCQNWpBah+F0DUvxQ+SxI0nykG8+SwgOLrRhTmOYAxxH6B/U1qBfrzOyQmreJRW6rdnLfX189pCezupcjTZiIuXR1FXhdNe4rjjwhSrhsZabsH73lVl6pTJfZCVN8ZSDJdmZOLk40Hs+39G2HrYUSQVHNQZWMJPLRwf8ha02V1azaQl5kemjb2VwCosloNuizVkVRwzVV0rWnoQDVjhsY2xX7askEnCxqllyaiuhqYbrZqchnENAjbhwpR98Qy/UexLsNp1bpvbgRhBAeRI5qq2NB2SKWOZP3Mr0R1yff7k0+OJ1gKaQ6B5JwV5pqYTSHBMO6PlVOKhOlj5W3IOqqLVdMKg8e3HVhavo6AUw==
{{- end }}
