name: Schema

on:
  push:
  pull_request:

jobs:
  generate:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Install Rover CLI
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.23.0-rc.3 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Install graphql inspector 
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: global add @graphql-inspector/cli graphql

      - name: Checkout main branch
        uses: actions/checkout@v4.1.4
        with:
          ref: main

      - name: Compose old Supergraph Schema
        run: >
          rover supergraph compose
          --config supergraph-config.yaml
          --elv2-license=accept
          > old_supergraph.graphql

      - name: Upload old Schema Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: old_supergraph.graphql
          path: old_supergraph.graphql

      - name: Checkout Source
        uses: actions/checkout@v4.1.4

      - name: Compose Supergraph Schema
        run: >
          rover supergraph compose
          --config supergraph-config.yaml
          --elv2-license=accept
          > supergraph.graphql

      - name: Download old Schema Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: old_supergraph.graphql     

      - name: Compare New Schnema with Old Schema
        continue-on-error: true
        run: graphql-inspector diff old_supergraph.graphql supergraph.graphql --federation > changes.txt

      - name: Generate Diff
        run: |
          git diff --no-index old_supergraph.graphql supergraph.graphql > diff_output.txt

      - name: Read Diff Output
        id: read_diff
        run: |
          echo "DIFF_OUTPUT=$(cat diff_output.txt)" >> $GITHUB_ENV

      - name: Comment PR with schema diff
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        if: github.event_name == 'pull_request'
        with: 
          message: $DIFF_OUTPUT
          comment_tag: schema_diff
          mode: recreate

      # - name: Check for breaking changes
      #   id: check_breaking_changes
      #   run: |
      #     if grep -q 'No breaking changes' changes.txt; then
      #       echo "breaking_changes=false" >> $GITHUB_ENV
      #     else
      #       echo "breaking_changes=true" >> $GITHUB_ENV
      #     fi

      - name: Upload New Schema Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: supergraph.graphql
          path: supergraph.graphql
      
  publish:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    needs:
      - generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.4

      - name: Setup Helm
        uses: azure/setup-helm@v4.0.0

      - name: Download Schema Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: supergraph.graphql     
          path: charts/supergraph

      - name: Package Chart
        run: helm package charts/supergraph

      - name: Generate Image Name
        run: echo IMAGE_REPOSITORY=oci://ghcr.io/$(echo "${{ github.repository }}-supergraph" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]') >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: helm push $(ls supergraph-*.tgz) ${{ env.IMAGE_REPOSITORY }}
